version: '3'
volumes:
  dados:
services:
  db:
    image: postgres:9.6
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      # Volume dos dados
      - dados:/var/lib/postgres/data
      # Scripts
      - ./scripts:/scripts
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql