// import './tipos/variaveis'
// import './tipos/array'
// import './tipos/enum'
// import './tipos/enum_const'
// import './tipos/enum_tipo'
// import './tipos/funcoes'
// import './tipos/funcoes_tipo'
import './tipos/objetos'