// import './tipos/variaveis'
// import './tipos/array'
// import './tipos/enum'
// import './tipos/enum_const'
// import './tipos/enum_tipo'
// import './tipos/funcoes'
// import './tipos/funcoes_tipo'
// import './tipos/objetos'
// import './tipos/desafioProduto'
// import './tipos/tipoUniao'
// import './tipos/never'
// import './tipos/null'
// import './tipos/desafioDoCapitulo'
// import './oo/classe_1'
// import './oo/classe_2'
// import './oo/classe_3'
import './oo/classe_4'